
CREATE TABLE ANSWERS
(
  ANSWER_UID VARCHAR(200) NOT NULL COMMENT '답항 UID',
  ANSWER     VARCHAR(200) NOT NULL COMMENT '답항',
  PRIMARY KEY (ANSWER_UID)
) COMMENT '설문 답항';

CREATE TABLE PARTICIPANTS
(
  PARTICIPANTS_UID VARCHAR(200) NOT NULL COMMENT '참여자 UID',
  NAME             VARCHAR(200) NOT NULL COMMENT '이름',
  PRIMARY KEY (PARTICIPANTS_UID)
) COMMENT '참여자';

CREATE TABLE QUESTIONS
(
  QUESTIONS_UID VARCHAR(200) NOT NULL COMMENT '문항 UID',
  CONTENTS      VARCHAR(200) NOT NULL COMMENT '문항 내용',
  PRIMARY KEY (QUESTIONS_UID)
) COMMENT '설문 문항';

CREATE TABLE RESULT
(
  PARTICIPANTS_UID VARCHAR(200) NOT NULL COMMENT '참여자 UID',
  ANSWER_UID       VARCHAR(200) NOT NULL COMMENT '답항 UID',
  QUESTIONS_UID    VARCHAR(200) NOT NULL COMMENT '문항 UID'
) COMMENT '결과/통계';

ALTER TABLE RESULT
  ADD CONSTRAINT FK_PARTICIPANTS_TO_RESULT
    FOREIGN KEY (PARTICIPANTS_UID)
    REFERENCES PARTICIPANTS (PARTICIPANTS_UID);

ALTER TABLE RESULT
  ADD CONSTRAINT FK_ANSWERS_TO_RESULT
    FOREIGN KEY (ANSWER_UID)
    REFERENCES ANSWERS (ANSWER_UID);

ALTER TABLE RESULT
  ADD CONSTRAINT FK_QUESTIONS_TO_RESULT
    FOREIGN KEY (QUESTIONS_UID)
    REFERENCES QUESTIONS (QUESTIONS_UID);
